### ISSUE TITLE
for all user texts: use what is well known

### ISSUE THREAD

**Issue by soloturn** [actionless/pikaur#258]
keep existing names in pikaur source code, user dialog, and documentation. 

examples are pacmans "skip" flags, which are presented with different texts in pikaur and lead to confusion, in wiki when describing them, and for users. see commit
https://github.com/actionless/pikaur/commit/3688d828591d307c6864c3b5ad8c1f581396b865

"handle" in pikaur source code is "skip" in the flags passed. "skipint" which is skipping checksum and pgp source file integrity ecomes "skip all validity ..".

**Comment by actionless** [comment]
sorry, i didn't got what do you mean, you're proposing to write flags in the build recovery prompt?

```
:: Try recovering?
[R] retry build
[p] pgp check skip (--skippgpcheck)
[c] checksums skip (--skipchecksums)
[i] ignore architecture (--ignorearch)
[v] skip all validity checks (--skipinteg)
------------------------
[s] skip building this package
[a] abort building all the packages
```

btw i am also going to add there a new entry, `[d] delete build dir and try again`, which could be useful if --keepbuild is passed (don't remove build directory between build) and build fails because of not clean directory, for example, repo url changed and it can't clone to the same dir name
