### ISSUE TITLE
Cursor jumps like crazy in the output

### ISSUE THREAD

**Issue by kyak** [actionless/pikaur#326]
```
Pikaur v1.3.4
Pacman v5.1.1 - libalpm v11.0.1

```
A picture worth a thousand words:
![call](https://user-images.githubusercontent.com/699631/50293948-d3145f80-0485-11e9-9213-5d37d3e2e0a2.gif)

Former pacaur user here.. Both pacman and pacaur don't exhibit such behaviour.
I'm using lxterminal and screen.

**Comment by actionless** [comment]
that's a known issue because of the way how pacman is wrapped by pikaur:

instead of using potentially dangerous pacman options (--nodeps --ask --noconfirm and other) which could damage local package database or its consistency pikaur is opening pacman in a virtual terminal and sending "Y" reply to the answer "Do you want to proceed"

if you want you could request to make this behavior optional

**Comment by kyak** [comment]
That would be strange to trade off safety for a visualization glitch, I doubt anyone would choose to use such behaviour.

Is there something that can be done without changing the way how pacman is wrapped by pikaur? Maybe you could buffer complete lines before sending them back? Or maybe there are some control codes to prevent cursor jumping?

**Comment by actionless** [comment]
trade off will be not safety but need to manually press "Y" on the keyboard several times during the build and installation of build deps ,removal of build deps, installation of built package

that would break progressbars

**Comment by kyak** [comment]
OK then.

How about disabling cursor alltogether when dealing with progress bars?

You could use '\033[?25l' to disable cursor and '\033[?12;25h' to enable it again. I'm just not sure where is the best place to do that (I was playing around at def write_buffer_contents).

**Comment by actionless** [comment]
cursor shouldn't be always hidden -- for example if pacman ask about package providers (alternatives) user input is needed or if during sysupgrade repository suggets to replace the packages

**Comment by kyak** [comment]
Yes, it shouldn't be always hidden - only when a progress bar is going on. More specifically, it should be hidden when it is known for sure that user interaction is not required (for example, download or installation is in progress).

**Comment by actionless** [comment]
i think determining that could be flaky, but if you feeling like you close to some robust solution -- you can try to tackle it

and i hope one day in pacman it will be a flag to skip only 'Do you want to proceed?` "main" prompt without skipping the rest of interactive questions (which will allow to drop the virtual tty hack)

**Comment by kyak** [comment]
Just another thought. If the only purpose of the "virtual tty hack" is to send "Y" to the "Do you want to proceed?" question, then maybe you could use **pexpect** to achieve that?

**Comment by actionless** [comment]
in early prototypes i didn't got the same performance with preserving colored output at the same type

feel free to try, if your implementation will be faster and output will be still colored -- i'll be happy to merge it

**Comment by m-khvoinitsky** [comment]
This issue is caused by the fact that for some reason you decided to throttle stdout writes. Obviously, pacman knows terminal width and writes the whole lines of progressbar at once plus carriage return which results in cursor always be at the beginning of the line. By throttling output writes you break this behavior.

#442 removes this behavior and fixes this issue.

**Comment by actionless** [comment]
Thanks, I gonna review it in couple of hours when I get home

Just some quick answers on design decisions ive made previously:

1) the reason for throttling was cpu usage
2) for reading only one byte -- if output finished before x*4096 bytes read
-- as far as I remember it was just leaving subprocess stuck (also not sure
how slow-going progressbar gonna look when reading more than 1 byte)

So gonna see on practice if those points are still actual

**Comment by m-khvoinitsky** [comment]
1. Because write_buffer_contents only called when something is written to the buffer, it won't make more load than pacman itself. I've tested it roughly and haven't noticed any CPU load at all (may be it would be if the data is written byte by byte).
2. `read(size)` would read all available data in the buffer but no more than `size` without blocking. `read()` (without arguments) will indeed block waiting for EOF but it won't be EOF because pacman itself is waiting for user input and won't exit. So there shouldn't be any problems.

**Comment by actionless** [comment]
i've already did some quick testing -- so far it looks good, thanks

i'll give it to more time locally to make sure there are no regression, and if all still good gonna merge it tonight or tomorrow morning

**Comment by kyak** [comment]
@m-khvoinitsky thanks a lot! A couple of lines patch, and such a great enhancement! Although I've somewhat got used to the jumping cursor throughout the last year of using pikaur, I still appreciate your improvement so much!
