### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by hakavlad** [actionless/pikaur#342]
I've noticed you don't have a CoC yet. Care to accept one? I would suggest accepting [WTFCoC](https://github.com/mniip/wtfcoc) CoC, believe me it's an incredible CoC, everyone should accept it or at least try it. You would be amazed how great of a CoC it is.

Here is how you can accept a CoC: https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/

Please do, okay?

**Comment by actionless** [comment]
what was the reason for removing yours? https://github.com/hakavlad/nohang/commit/4b67b2f131abf2d378b657db65084d59af838745

**Comment by hakavlad** [comment]
I think that I do not need it yet (I was visited by too few SJW).

**Comment by actionless** [comment]
But actually, since the topic was touched, as a nohang package maintainer i'd like to raise a concern about changing Code of Conduct without prior notice. I think some users could count it as an attack on their freedoms (since their interests became not anymore guarded by that document without any notification).

However going into details, it seems what that particular document is not maintained anymore (for example link in the description isn't working, there are unsolved issues hanging around). I think it could be good idea to do some research and find a similar document with a bigger/more active community which still will be aiming to protect the same freedoms as the previous.

**Comment by hakavlad** [comment]
>that particular document is not maintained anymore

IMHO it's not a problem.

**Comment by hakavlad** [comment]
>find a similar document

You can fork it and fix what you want.

**Comment by hakavlad** [comment]
see also https://github.com/domgetter/NCoC

**Comment by actionless** [comment]
NCoC looks still maintained, though it's assuming to limit contributions from non-adult developers. While at the beginning of Nim programming language a lot of useful stuff was contributed by (at that time) 13 or 14 y/o guy, so that case study learning me not to make such assumptions

also there is https://www.gnu.org/philosophy/kind-communication.html but it goes too offtopic from the actual software development. anyway i still would like to point out RMS quote from its announcement, https://lists.gnu.org/archive/html/info-gnu/2018-10/msg00001.html:

> A code of conduct states rules, with punishments for anyone that violates them. It is the heavy-handed way of teaching people to behave differently, and since it only comes into action when people do something against the rules, it doesn't try to teach people to do better than what the rules require.

i would continue looking for something similar to NCoC but without ageism involved

**Comment by hakavlad** [comment]
see https://github.com/domgetter/NCoC/issues/19#issuecomment-325253352

**Comment by actionless** [comment]
i don't like phrasing which require so verbose explanation to be understood unequivocally

**Comment by hakavlad** [comment]
>If you want to modify the NCoC for your own use, like @teo-tsirpanis, you are more than welcome to do so.

https://github.com/domgetter/NCoC/issues/19#issuecomment-412267066

What about adopting the following:

>Contributor Code of Conduct
This project adheres to No Code of Conduct. We accept anyone's contributions. Nothing else matters.
For more information please visit the No Code of Conduct homepage.

or

>Contributor Code of Conduct
We accept anyone's contributions. Nothing else matters.

**Comment by actionless** [comment]
let's give some time to a PR to be reviewed

for me important to have community of co-minded behind CoC, so forking wouldn't be a great option

**Comment by hakavlad** [comment]
IMHO PR will not be accepted. This matter have been discussed yet - https://github.com/domgetter/NCoC/issues/19

**Comment by actionless** [comment]
let's give it one more try or 

>  continue looking for something similar

**Comment by actionless** [comment]
> Repository owner locked as resolved and limited conversation to collaborators 9 minutes ago

lol, super-adult guy

**Comment by hakavlad** [comment]
It's not court. This is a private territory with the possibility of private discrimination by the creator of the project.

**Comment by actionless** [comment]
but that's not those ideals which i would like to promote by using their document

that's a good illustration of the fact what even code of conduct with pseudo-denying content still serving to endorse police behavior without adding transparent court system behind it

**Comment by hakavlad** [comment]
What about doc like this https://www.kernel.org/doc/html/v4.17/process/code-of-conflict.html

**Comment by actionless** [comment]
text seems fine to me (though i'd prefer stating the same in 10 or more times less words used)

and it also not meets one of requirements -- to be backed by a big enough community

**Comment by jonas-schievink** [comment]
How about adopting the [Contributor Convenant](https://www.contributor-covenant.org/)? It's nice in that it actually spells out what kind of behaviour is considered appropriate and what isn't. Linux has since switched to it, and it seems to be used by many other projects too.

**Comment by actionless** [comment]
now, it was created by corporations to turn people into slaves by using thought-up reasons

**Comment by hakavlad** [comment]
>strongly opposes natural libertarian views

What about writing NAPCoC?

**Comment by actionless** [comment]
after spending some blue hunnids on a professional diversity consultant (professor of evolution and gender studies of johto university) we glad to announce  the comprehensive guidelines which should help to ensure healthy working environment, encourage behavior standards and improve how the community deal with the ethical dilemmas, prejudices and gray areas that could be encountered

**Comment by hakavlad** [comment]
>50% of the application current source code

How do you calculate it? By lines number, by commits number? It is not described in CoC.

**Comment by actionless** [comment]
thanks, good point

i propose counting by SLOC, does it sounds reasonable?

**Comment by rafasc** [comment]
> i propose counting by SLOC, does it sounds reasonable?

Not really. 

Imagine I make a formatting PR to make code comply with some formatting guidelines, and it touches the majority of the code? 

Why should it give me the ability to change the CoC? 

Why should translators and documentation contributors have more weight in the CoC decisions? Just because their contributions are usually more verbose.

Why should contributors that do not contribute directly to the source code (Imagine someone is tasked with the job of triaging bugs) have less voice? 

SLOC/commit count and similar options are all flawed ideas for this type of decision. They only promote writing bad code/history in order to "pump stats".

**Comment by actionless** [comment]
reformatting all the code would also break `git blame` and other related things, so i'm not sure it's generally a good idea to do (especially when project was already written with continuously integrated flake8 checks)

i don't think what documentation, code comments and localization files are counted as SLOC

> Why should contributors that do not contribute directly to the source code (Imagine someone is tasked with the job of triaging bugs) have less voice?

think of it as of good motivation to move from triaging the bugs into fixing them ^__^


however please propose alternative suggestions which you think could make it practically easier to measure the technical contribution to the project, they will be carefully reviewed and could be taken into consideration

**Comment by rafasc** [comment]
Measuring the technical contribution to the project is hard. I think we both know that.

The PR was just a simple example. What I was trying to say with that is that the value of a contribution is not directly proportional to the number of lines of code.

>i don't think what documentation, code comments and localization files are counted as SLOC

Didn't take long to show SLOC being bad. Because documentation, comments and localization are good technical contributions. 

And it doesn't take long to come up with other problematic situations when using the SLOC metric. 

E.g. Person A makes a PR with 500 lines fixing a problem. It gets accepted because it fixes an important issue. Now that the problem is solved, Person B really takes their time to investigate the root cause and manages to replace those 500 lines with 50.

1. Is the 50 lines contribution from Person B less important than the 500 from Person A?  
2. All lines from Person A were deleted by Person B. Does A still get a voice? Are you going to blame the entire history? That's not an easy task.

As of now, it doesn't really matter because it's clear you hold more than 50% in any sane way to make that count, but that same fact makes that part of CoC a bit useless.

Sadly, I don't have a better way to measure it either. What I do know is that SLOC is biased, promotes writing bad code, and is easily exploitable. Especially since there isn't a fair/clear answer on how to count said lines.

(I should probably stop wasting my time in github comments as they won't count as technical contributions... :upside_down_face:  )

**Comment by actionless** [comment]
> Are you going to blame the entire [git] history?

yeah, that could be done, i think there are already quite a lot of scripts and web apps which could show such kind of statistics for a publicly accessible repository

> but that same fact makes that part of CoC a bit useless.

that's an attempt to make document design scalable over the time

> Sadly, I don't have a better way to measure it either.

being said, that means what i don't have any better options to consider -- any other ideas i was evaluating in mind -- had much higher risk of subjectivity

**Comment by actionless** [comment]
or actually it would be more fair to make the procedure of adjusting Code of Conduct the same as a  License -- any further changes should be accepted by all the authors or their code must be rewritten?

quite an interesting question to think about

**Comment by hakavlad** [comment]
In fact, you can live without CoC. Why do you need CoC?

**Comment by actionless** [comment]
hm, wasn't you the one who created this issue? :P
