### ISSUE TITLE
[Suggestion] search, select and install packages

### ISSUE THREAD

**Issue by JulioJu** [actionless/pikaur#351]
Hi,

Thanks for your work.

If you do `yaourt` without -S,  we could searching for a package and a menu appears : `Enter n° of packages to be installed (e.g., 1 2 3 or 1-3)` . 

What do you think about this feature ? I believe it's a very cool feature, if we want install lot of packages that match a search criteria. 

Thanks in advance ;-) .

**Comment by actionless** [comment]
thanks for your suggestion, it doesn't sound complicated to be implemented

**Comment by mattia-b89** [comment]
Great work @actionless !
But I want to share with you what I think is a _little issue_:  
talking about the message `[...]you want to install (default: 0):`; I think zero (0) is _misleading/odd_ choice because usually zero (0) means "no/none" and if I choose this answer I think no one package will be installed at all  

_-> **What packages do you want to install?** -> 0 -> **none** -> no one package will be installed_

I think we have two _better_ options/alternatives:

1. start packages numbering from one (1), not from (0) and **change** default answer to one (1); because it is logical to guess that the first package listed is just the one the user want
2. start packages numbering from one (1), not from (0) and **keep** default answer to zero (0) but **change** default behaviour to simply exit the program, for the reason explained above;

**Comment by actionless** [comment]
thanks, i've released a new version

also while testing it again find a bug with sorting order which fix also included to the release
