### ISSUE TITLE
aurvote integration

### ISSUE THREAD

**Issue by actionless** [actionless/pikaur#363]
aurvote support was one of key features of yaourt back then, and since it's officially retired by now i think it would be useful to adopt that idea with the time

**Comment by mattia-b89** [comment]
`Vote count`, which is already implemented (as well as `popularity`), it's great!  
I disagree instead for a "complete" aurvote support (vote/unvote for a package) for the points below:  
- it's not the only feature which needs to use the AUR webpage (toggle on/off notification, flag out-to-date, submit a request), thus I need anyway to open the browser...  
- AUR voting is a _serious_ thing: users should vote/unvote only after you installed and "tested" a package, not just before/after you installed it  
- **every time** you (update)install a package, pikaur asks you if you want to (un)vote the package: it is a waste of time because this operation is done only once per package  
- how to remove a vote?

**Comment by actionless** [comment]
thanks for elaborating on this, @mattia-b89 !
i think it's reasonable to close it
