### ISSUE TITLE
Do not delete build dependencies

### ISSUE THREAD

**Issue by JulioJu** [actionless/pikaur#370]
Hi !

Is it possible to no delete package needed for build dependencies ? 

In Yaourt, packages dependencies for build are not deleted

Thanks in advance !

**Comment by actionless** [comment]
there is no such option, but it should be complicated to implement such flag

**Comment by zynexiz** [comment]
Personally, that's what I really like about pikaur. I don't like a cluttered system with unused packages laying around that's rarely used. If of some reason you want some of the packages anyway, install then manually. Pikaur don't remove them if they are installed outside pikaur.

**Comment by stertingen** [comment]
When installing ros-melodic-desktop(https://aur.archlinux.org/packages/ros-melodic-desktop/), this is a pain. The build dependencies are installed and removed per package. (Which also have build dependencies from the AUR!) So pikaur spends a lot of time installing and removing build dependencies instead of building packages.

A nice option would be to resolve build dependencies for every package at the very beginning, install them all, and after every package is built, remove them all.

**Comment by JulioJu** [comment]
@stertingen or not remove build dependencies ! 

It could be cool to let the user the choice to remove or not build dependencies at the end of the install process. 

Note:

> Running
>
> pacman -Qdt
>
> will get you a list of packages that were installed as dependencies but are no longer needed > by any package.  These can be safely uninstalled.
> https://bbs.archlinux.org/viewtopic.php?id=89140


It could be cool that `Pikaur` run ***optionally*** this command at the end of the installation !

**Comment by actionless** [comment]
ok, since user demand on that have raised over the time, i'll indeed add that option soon
