### ISSUE TITLE
Show dependency list after the user has edited PKGBUILD

### ISSUE THREAD

**Issue by AETolouee** [actionless/pikaur#372]
Its a simple change with a simple reason: if the user removes/adds some dependencies from the PKGBUILD then the list shown will not be correct. pikaur should ask user to edit the PKGBUILD first and then process the edited file.

**Comment by Mako88** [comment]
Along with this, it shouldn't ask to remove packages that are dependency conflicts before modifying the PKGBUILD, since the modified PKGBUILD may no longer have those conflicts.

**Comment by azrdev** [comment]
An example for this issue is installing `latex-tuddesign` and then trying to install `latex-tuda-ci` (which `replaces` the former) without removing it: pikaur first asks if the conflicting package should be removed (and aborts if replying No), before giving me a chance to remove the `replaces` from the PKGBUILD

**Comment by actionless** [comment]
seems it gonna be superseded by https://github.com/actionless/pikaur/issues/427

**Comment by actionless** [comment]
user can edit pkgbuild in two cases:

1) during review of build files
2) if build failed it's an option to edit its pkgbuild


now for case 1 this feature is implemented

**Comment by actionless** [comment]
now it should work in both cases, please test with `pikaur-git`
