### ISSUE TITLE
feature request: Remove dependency from sudo (use su -c)

### ISSUE THREAD

**Issue by carpikes** [actionless/pikaur#373]
```
pikaur -Vq:
Pikaur v1.4.3
Pacman v5.1.3 - libalpm v11.0.3
```
Before using pikaur I was used to yaourt. If you don't have `sudo` installed, yaourt runs `su -c` only when necessary (e.g. `pacman -U`).
pikaur instead has sudo as dependency and it does not start if sudo is not installed.

**Comment by mattia-b89** [comment]
Honestly, I don't know at what point pikaur invokes `sudo` but I think it is necessary to sports the **_"without user interaction"_** feature.  
Anyway, the most important reason why I write here, is to _remember_ that `sudo` is a member of `base-devel` group, the bundle of software needed to build, compile, install software from source on Arch Linux, that's AUR. And AUR is one of the reason why `pikaur` exists since it's an AUR helper!  
_thus_ 99% of people using `pikaur` will and should have `sudo` (or better the entire _base-devel_ group) installed in their system
```
[mattia@arch-xps ~]$ pacman -Qi sudo
Name            : sudo
Version         : 1.8.27-1
Description     : Give certain users the ability to run some commands as root
Architecture    : x86_64
URL             : https://www.sudo.ws/sudo/
Licenses        : custom
Groups          : base-devel
```
**_Long story short_**, I think this feature doesn't have a reason of being _(or a very low priority...)_

**Comment by actionless** [comment]
> sudo is a member of base-devel group, the bundle of software needed to build, compile, install software from source on Arch Linux
