### ISSUE TITLE
Use of pyalpm

### ISSUE THREAD

**Issue by AladW** [actionless/pikaur#43]
Going by https://github.com/actionless/pikaur/pull/41#issuecomment-368362210, I would suggest to make use of tools like `pyalpm` and `expac` to remove some in-house code from `pikaur`.

https://github.com/jelly/pyalpm

**Comment by eli-schwartz** [comment]
In #30 there is actually one lonesome code fragment that calls libalpm via **ctypes** just to avoid shelling out to vercmp.

**Comment by actionless** [comment]
i don't mind using libalpm which comes with pacman, however i have my reason not to use pyalpm:
https://github.com/actionless/pikaur/pull/41#issuecomment-368362210

**Comment by AladW** [comment]
pyalpm is in extra?

https://www.archlinux.org/packages/extra/x86_64/pyalpm/

**Comment by actionless** [comment]
good, in that case, i'll consider refactoring

**Comment by actionless** [comment]
did some already:

1535c72
65c4740
5e423b8

**Comment by actionless** [comment]
idk what else i can refactor, except for package search  (-Ss)

**Comment by actionless** [comment]
closed in da4c4a8

feel free to reopen

thanks for your suggestions!

**Comment by actionless** [comment]
btw search became quite slower (and with more search words it's more noticeable) after using pyalpm instead of calling `pacman -Ss`

could you have a look in the commit if i'm doing smth wrong there?

**Comment by AladW** [comment]
@actionless if there's a performance issue with pyalpm it might help to report it at https://github.com/jelly/pyalpm/issues

**Comment by actionless** [comment]
i don't think it's issue in pyalpm itself, i more feeling like it's just the difference between C and Python code, but yeah, it won't be bad to double-check what should be the expected performance difference with pacman

**Comment by actionless** [comment]
@AladW 

```sh
$ time ./pikaur.py -Ss mpv > /dev/null  # with disabled AUR
Searching... [##-]
real 0.71
user 0.61
sys 0.06

$ time pycman-sync -s mpv > /dev/null
real 0.41
user 0.37
sys 0.03

$ time pacman -Ss mpv > /dev/null
real 0.37
user 0.34
sys 0.03
```

so it looks something wrong on my side

**Comment by actionless** [comment]
@AladW i think i was initially right with the idea to just implement html parsing on client side -- my point about control freaks still valid (judging by reaction on my patch) so i'm just feeling like i am uselessly spent my time, intead of really fixing the problem for the users

**Comment by AladW** [comment]
It's hardly control freaks when people ask about respecting basic patch submission etiquette. If it bothers you I can submit it to the mailing list with you as commiter, no problem.

N.b. I think you meant to reply on the other issue.

**Comment by actionless** [comment]
i am interested in getting aur rpc fixed, not in getting the credits in commit history, so i don't mind whatever way you prefer to apply a patch there

wasn't you (i mean not you as person but you as a team) considering what installing some a bit more modern code-review system could actually take less time and effort than manually checking formatting of mail messages and so on?

yup, my  bad, that's a wrong thread actually, this one can be closed btw since i don't think more work on pyalpm-related stuff need to be done here

**Comment by AladW** [comment]
>considering what installing some a bit more modern code-review system could actually take less time and effort than manually checking formatting of mail messages and so on?

At one point flyspray will be replaced by a modern system, e.g. `gitlab` was put under consideration, but I believe that it got on the backburner a while ago...

>this one can be closed btw since i don't think more work on pyalpm-related stuff need to be done here

:+1:

**Comment by actionless** [comment]
i know gnome projects switched to gitlab some time ago, mb you know some people to ask about the impressions

**Comment by actionless** [comment]
or mb configuring flyspray to allow uploading diff files as valid patches?

**Comment by eli-schwartz** [comment]
Um, you can in fact upload any sort of file you want to flyspray. People frequently do in fact upload *.patch files.

> wasn't you (i mean not you as person but you as a team) considering what installing some a bit more modern code-review system could actually take less time and effort than manually checking formatting of mail messages and so on?

Is it manual, if I tried importing your email into my aurweb git clone and it failed claiming that the patch was corrupted? And I then responded twice to you telling you how to do it correctly?

git-send-email is at least modern enough that Linux and git themselves are the flagship projects doing development entirely via email and git-send-email. It works pretty well for them.

Is patchwork modern enough, then? We have one of those too. https://patchwork.archlinux.org/project/aur-dev/list/

As for gitlab, no one wanted to take on the burden of trying to self-host it, it is in the official repos for long enough to prove that having a reliably working setup is not entirely trivial. We're not willing to consider, as a distribution, depending altogether on thirdparty infrastructure, and if we did host gitlab we would still have to figure out how to limit it to official projects anyways, so we might not hand out free accounts regardless. If we did, we would need to enable some sort of mailing list hook so Arch devs could continue to use their preferred solution (mailing lists).

git-send-email is dead simple, far more so than copy-pasting patch files into emails *or* attaching them to bug reports. I'll grant that it's much harder for people whose workflow is using github.com to edit files and have github generate commits for them. It's a tossup for people who push to github via the command line and then go to the web interface to create a pull request versus using an email tool to send a patch -- on the one hand, PR models are more integrated than mailing lists, on the other hand, they require creating Yet Another Account with the theoretical self-hosted gitlab and switching contexts a couple times vs. using a command-line email tool then switching to `$EMAIL_CLIENT`.

**Comment by eli-schwartz** [comment]
> point about control freaks is still valid (judging by the reaction on my patch) so i'm just feeling like i am uselessly spent my time, intead of really fixing the problem for the users

Also this is incredibly dishonest for reasons you are surely well aware of (including but not limited to your baseless insinuation that we have no interest in accepting your work, and your claim that we reacted in a "control freak" manner due to our inability to actually use the patch you submitted which suffered from a fairly neutral concept called file corruption), and simply makes me think you are a toxic pox upon the community. How is that for insults and mudslinging?

Okay, great, now we've both calmed down how about you rephrase that complaint in a bit more of a reasoned manner? :)

**Comment by actionless** [comment]
I was actually told what the mailing list is a only way to submit a patch so that initially left quite a bad impression. Because despite for your advocating for git-send-email in combination with the maillist workflow it's still not working well in some cases, like accessing from public or work station.

now, considering the other available options, i have no compains if i can just submit a raw patch file to flyspray and reviewers will receive auto-generated mail in expected format
