### ISSUE TITLE
Password query of sudo is hidden

### ISSUE THREAD

**Issue by roussak** [actionless/pikaur#506]
Steps to reproduce the issue:

1. Run the pikaur to install some package from the AUR which needs to install dependecies. The sudo's password query should be shown. (BTW, IMHO, it is a strange behaviour: why does it need at this stage?)
2. At the stage when there will be shown the query about the PKGBILD file editing, wait longer than the sudo's password expiration time.
3. When the process will be continued, the program looks hanged at the stage "Installing repository dependencies for _package name_". After I interrupted the program with SIGINT, there was shown the "[sudo] password for _user name_:" prompt and the "sudo: timed out reading password" message some time later.

**Comment by actionless** [comment]
i can't reproduce it with the current steps

**Comment by roussak** [comment]
It isn't being reprocable on my side too... Probably, it was an issue if my console.

**Comment by actionless** [comment]
for me that happened only when i once put to hibernate my laptop WHILE pikaur was working

but you never "allowed" to do that, because if it would run the pacman upgrade for some essential components (like kernel) and will be hibernated while doing so the system might not ever return from that hibernate

**Comment by roussak** [comment]
Yes, I put to hibernate my laptop between steps 2 and 3 too. So, it looks like there is no any reason to keep this issue opened.
