### ISSUE TITLE
IPV6 download

### ISSUE THREAD

**Issue by switit** [actionless/pikaur#546]
I'm trying to install pikaur on my ipv6 only server and found that the package cannot be downloaded from github which doesn't support ipv6. Is there another source that support ipv6?

**Comment by actionless** [comment]
have no idea

**Comment by baj0k** [comment]
Hey @switit,
For you to be able to clone the repository via ipv6, somebody would need to maintain a mirror/fork on a server that would support this protocol. 

You could do it by yourself, however it would require some work on your side to ensure that the fork is up to date with the upstream repository (in this case the github one). Not mentioning the maintenance of the server itself.

You can try and convince repository owners to move a project to different service or maintain a mirror repository on the ipv6 enabled server. Unfortunately, even if one or two projects happen to fulfill those expectations you will still face the same issue sooner than later.

You could also search for a mirror/fork maintained by a third party (I guess that's what your were asking in the question), but I would strongly advise against it.
Relying on a third party to regularly update the code and not to inject anything malicious is a potential security issue and it might result in your server being compromised. Especially when we are talking about a package manager kind of software. 

What's the real issue here is that Microsoft didn't enable ipv6 support on GitHub yet and until that happens the only reasonable workaround is to use a 6to4-relay or tunneling in order to access the ipv4-only part of the internet from your server.

@actionless Since the repository isn't hosted/mirrored anywhere else and the issue applies more to the GitHub itself than to the pikaur I suggest closing the issue.

**Comment by actionless** [comment]
thanks for analyzing multiple issues here @baj0k , appreciate this a lot!
