### ISSUE TITLE
not all user environment variables are bypassed into $EDITOR

### ISSUE THREAD

**Issue by real-or-random** [actionless/pikaur#742]
```
Pikaur v1.18.2
Pacman v6.0.2 - libalpm v13.0.2 - pyalpm v0.10.6
```

##### [Optional] Prerequisites:
Have this in the environment:
```
VISUAL="emacsclient --tty"
```

##### Description:

pikaur can't open the emacs (client) anymore. (I run emacs as daemon, and then you can use use `emacsclient` to open a new editor view. I think this regression is caused by https://github.com/actionless/pikaur/commit/075e7eb2d240e8ccbfdb3e5deb24a6872cc828b7:

The log shows:
```
Do you want to edit PKGBUILD for xyz package? [Y/n] 
emacsclient: Should XDG_RUNTIME_DIR='/run/user/1000' be in the environment?
emacsclient: (Be careful: XDG_RUNTIME_DIR is security-related.)
emacsclient: can't find socket; have you started the server?
emacsclient: To start the server in Emacs, type "M-x server-start".
emacsclient: No socket or alternate editor.  Please use:  
```

Indeed, `sudo --user=<myuser> --preserve-env=XDG_RUNTIME_DIR  emacsclient test` works whereas `sudo --user=<myuser>  emacsclient test` does not work. I think one solution is to `XDG_RUNTIME_DIR` to [`PRESERVE_ENV`](https://github.com/actionless/pikaur/blob/6402f6985ca057f3ba43d6e6272810a34643ddde/pikaur/privilege.py#L14) but I'm not convinced that this is the proper way. Other users/editors will likely need other variables. I think a proper solution is to run the editor in the initial environment and with the initial permissions (before elevating permissions), instead of elevating and dropping again.

A workaround for me is `VISUAL="env XDG_RUNTIME_DIR=/run/user/1000 emacsclient --tty"` .

**Comment by actionless** [comment]
>  I think a proper solution is to run the editor in the initial environment and with the initial permissions (before elevating permissions), instead of elevating and dropping again.

you can get back to that behavior with this config option: https://github.com/actionless/pikaur#privilegeescalationtarget-default-pikaur

but actually while we were discussing that new preserve-env thing with another user - it came up in conversation, that it might make sense in the future to make preserve-env list configurable via pikaur.conf

**Comment by actionless** [comment]
actually i just hit that problem myself trying to build `colmap-git` which require setting some env vars 😺 so i think to come up with some nice way for that tonight

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.

**Comment by veox** [comment]
The new version `v1.18.4` works as previously if `XDG_RUNTIME_DIR` is added to `preserveenv` in `~/.config/pikaur.conf` for me, with a similar case to that of OP's: `emacs --fg-daemon` running per-user (started via that user's `systemd` service), and `EDITOR` being set to `emacsclient -c -nw`.

At the root of the issue is this:

* `emacs` is run as a user's daemon;
* `EDITOR` is a call to `emacsclient`, which wants to connect to a daemon;
* `XDG_RUNTIME_DIR` is not preserved by default when elevating permissions (and probably rightfully so!);
* `emacsclient` doesn't know where to connect to.

-----

Passing `XDG_RUNTIME_DIR` has strings attached that lead who knows where.

I'd suggest also passing `ALTERNATE_EDITOR` in `preserveenv` instead; this seems a safer compromise.

Those of us who use `emacs` in daemon mode often know to set `ALTERNATE_EDITOR` to a non-daemon `emacs` or `mg` or anything.

**Comment by actionless** [comment]
@veox yeah you that would be weird to bypass `XDG_RUNTIME_DIR` - they should consider adding (if they don't have) an env var or cli arg for specifying to which emacs server to connect emacs-client 

as a workaround try changing here https://github.com/actionless/pikaur?tab=readme-ov-file#privilegeescalationtarget-default-pikaur to pacman (it would change sudo logic a bit)
