### ISSUE TITLE
you guys are dicks

### ISSUE THREAD

**Issue by groodle** [actionless/pikaur#815]
I loved your package but you guys are condescending twats. 

In response to #814 your error message is pure (grammaticaly incorrect) garbage. If you test for the presence of a package and then emit a warning WITH OUT mentioning the package you fucked up.

I installed all the build packages independently, everything worked. 

Not a single time in all your mocking, infantile responses did any of you mention the problem or the resolution.

Thanks for the hard work but fuck you guys.

**Comment by actionless** [comment]
if we're dicks - then you will enjoy sucking us 🐸

**Comment by aspizu** [comment]
I feel like this warning does not help naive or beginner users to get better
at using computers. The language will make them think of the entire open-source
and linux community to be elitists who don't want new people to use their
software because its so complex and hard to use. Being rude isn't encouraging
them to read the Arch Wiki. Its making them stop use Arch Linux and just think
we are always rude when they ask for help with the issues with their system.
If the message were to actually explain what is wrong with their system and
what can they do to fix it. You can not spoon-feed the solution, but still
be polite about it and encourage them to read the arch wiki.

**Comment by actionless** [comment]
they could just use any other of 50 existing aur helpers 🤷

as you could see from the flow of the conversation in other similar tickets - that's already a made decision, so i honestly fail to understand what makes you think that you could get another result by raising the same topic
