### ISSUE TITLE
New DECORATION seems to be broken

### ISSUE THREAD

**Issue by dschopf** [actionless/pikaur#835]
```
$ pikaur -Vq
Pikaur v1.26
Pacman v6.1.0 - libalpm v14.0.0 - pyalpm v0.10.6
```

##### [Optional] Prerequisites:

Install latest pikaur version

##### Description:

Old version showed `::`
![image](https://github.com/user-attachments/assets/5ad59db9-8c3b-47c1-bd37-a763241fe1c6)

New version shows `△`
![image](https://github.com/user-attachments/assets/06a933b7-2f43-4997-bde5-02731327193d)

**Comment by actionless** [comment]
https://github.com/actionless/pikaur/commit/f10c9563d35a9cc709d6b13b346ee9eb8aa4c52a

**Comment by Watkurem** [comment]
Funnily enough, this somehow breaks `rxvt-unicode-truecolor-wide-glyphs` (which is what I use, because normal `rxvt-unicode` messes with tmux for some weird colour-related reason).

Changing back to `:: ` (or `⚡️` for that matter) works perfectly fine.

@actionless I'll just do a custom build patch to deal with this, but making it configurable soon might be a good idea.

**Comment by actionless** [comment]
@Watkurem i'm pretty sure that's a bug in rxvt-unicode-truecolor-wide-glyphs

**Comment by Watkurem** [comment]
I agree, but I don't know how to fix that, while changing the character here lets me workaround it very quickly 😁

Just an extra reason to expose it in the config, I guess

**Comment by actionless** [comment]
![image](https://github.com/user-attachments/assets/0113c179-6bc6-4c1f-bde7-73879e64e65b)


mb with the time, but so far i'll prefer to leave that sign of support to Kurskian people who together with Ukraine are fighting for their liberty from the russian occupation

**Comment by actionless** [comment]
btw, a bit on offtopic side, have you tried `xst-git`? i've been an urxvt user for many years, and xst felt like a breath of fresh air
